import type { Metadata } from "next";
import { Mitr } from 'next/font/google';
import "./globals.css";

const mitr = Mitr({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'], // Include all available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mitr.className} antialiased mt-4`}>
        {children}
      </body>
    </html>
  );
}
